### ISSUE TITLE
Camera feed not shown from remote connection

### ISSUE THREAD

**Issue by wonx** [CoretechR/ZeroBot#1]
Since the IP address of the camera feed is hardcoded in the Touch.html file, it does not work if accessed from an external network. The IP should change dynamically to reflect the server's IP regardless from where it is accessed.

I have been able to solve this by replacing this line:

`<img src="http://192.168.1.10:9000/?action=stream" />`

with this short script:

```
<p id="demo"></p>

<script>
host = window.location.hostname;
img = '<img src="http://' + host + ':9000/?action=stream" />';
document.getElementById("demo").innerHTML = img;
</script>
```

**Comment by CoretechR** [comment]
Thank you, this is exactly what I have been looking for! Makes the setup much easier.
