### ISSUE TITLE
Touch control does not work, only mouse clicks are accepted

### ISSUE THREAD

**Issue by oskar456** [CoretechR/ZeroBot#2]
The web UI works on a computer but does not do anything on a mobile or tablet or even touchscreen computer. I guess this is due to `document.createTouch` being [deprecated and removed from most browsers](https://developer.mozilla.org/en-US/docs/Web/API/Document/createTouch#Browser_compatibility).

Changing condition on [line 215](https://github.com/CoretechR/ZeroBot/blob/master/Touch.html#L215) to `touchable = 'ontouchstart' in window,` fixes the issue partially for Android phones, however 2in1 devices still don't react to touches. Commenting out the whole `if (touchable) { … } else {…}`, leaving both branches in place seems to be working properly for me.

**Comment by CoretechR** [comment]
Thank you very much for bringing this to my attention and for providing a fix. I haven't noticed any problems yet, mostly because I'm using Chrome on PC or iOS for testing, which still support the feature. I will definitely look into it.

**Comment by ilyabelkin** [comment]
This code works well for the devices I could get hands on. Hope it helps!

```
	// Set the default
	touchable = true,
 	touches = []; // array of touch vectors;
 
	// TODO: quite fragile; find a better check for touch-ability as the Web standards evolve
	try {
		document.createEvent('TouchEvent'); }
	catch (err) {
		touchable = false;
	}	
```

**Comment by oskar456** [comment]
Is it really necessary to detect touch ability? Is there any harm by reacting both on mouse and touch events at the same time? If you have a touchscreen computer, you should be able to use both touches and mouse without switching anything.
